name: Construir Hectron APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # 🛡️ PARCHE DE EVOLUCIÓN: Forzando el motor a Node.js 24
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Obtener el código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar Flet
        run: pip install flet

      - name: Construir el APK
        run: yes | flet build apk

      - name: Subir el APK terminado
        uses: actions/upload-artifact@v4
        with:
          name: Hectron-Release
          path: build/apk/**/*.apk
